##七牛云的key
qiniu:
  accessKey: jgjWeh4eLhm6LVkqZfTLPc0pM_QVc5OxNh6CZSDB
  secretKey: jKHVUBKfff1qRncaI0jrhHPcSDD_ce8mjR52OHEH
  bucketName: jiang
  basePath: http://pq0c9fl0p.bkt.clouddn.com

## 百度推送
baidu:
  task:
    postUrl:  http://data.zz.baidu.com/urls?site=www.jiangbin.net.cn&token=AUnz5kdp9Fme8K2g
    baseUrl: https://www.jiangbin.net.cn

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zblog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: jiang-blog

#mynatis配置
mybatis:
  type-aliases-package: com.jiang.jblog.vo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml
#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file:
server:
  session-timeout : 3600
  port: 8080





